auto_login_url.settings:
  type: mapping
  label: 'Auto Login URL settings'
  mapping:
    secret:
      type: string
      label: 'Secret key'
    expiration:
      type: integer
      label: 'Expiration period'
    delete:
      type: boolean
      label: 'Delete on use'
    token_length:
      type: integer
      label: 'Token length'
    langcode:
      type: string
      label: 'Language code'
    _core:
      type: _core_config_info
