<?php


use Drupal\Core\Menu;
use Drupal\Core\Menu\MenuLinkInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Access\AccessResultInterface;
use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\RedirectResponse;


/**
 * Fetch Usernames with ID's for Checkbox.
 */
function _menu_per_user_fetch_names() {
  $user_query = db_select('users_field_data', 'u');
  $user_query->fields('u', array('uid', 'name'));
  $user_result = $user_query->execute()->fetchAll();
  $users = array();
  foreach ($user_result as $user_array) {
    if (!empty($user_array->name)) {
      $users[$user_array->uid] = $user_array->name;
    }
  }
  return $users;
}

/**
 * Implements function to check path existence.
 */
function menu_per_user_check_path($path){
  $path_check = db_select('user_menu_visibility','m')
    ->fields('m',['menu_path'])
    ->condition('menu_path',$path,'=')
    ->execute();
  $path_result = $path_check->fetchField();
  if ($path_result) {
    return TRUE;
  }
}

/**
 * Implements function to check path existence for anonymous user.
 */
function menu_per_user_anonymous_path($path){
  $path_check = db_select('user_menu_visibility','m')
    ->fields('m',['menu_path'])
    ->condition('menu_path',$path,'=')
    ->condition('user_id',0,'=')
    ->execute();
  $path_result = $path_check->fetchField();
  if ($path_result) {
    return TRUE;
  }
}

/**
 * Implements function to check path existence for other user(s).
 */
function menu_per_user_other_path($path){
  $path_check = db_select('user_menu_visibility','m')
    ->fields('m',['user_id'])
    ->condition('menu_path',$path,'=')
    ->condition('user_id',0,'!=')
    ->execute();
  $path_result = $path_check->fetchAll();
  $users = '';
  foreach($path_result as $paths){
	$users[$paths->user_id] = $paths->user_id;
  }
  return $users;
}

/**
 * Implements function to check path and uid existence.
 */
function menu_per_user_check_path_uid($path, $uid){
  $path_uid_check = db_select('user_menu_visibility','m')
    ->fields('m')
    ->condition('menu_path',$path,'=')
    ->condition('user_id',$uid,'=')
    ->execute();
  $result = $path_uid_check->fetchField();
  if ($result) {
    return TRUE;
  }
}

/**
 * Implements function to check menu name and uid existence.
 */
function menu_per_user_check_menu_name_uid($path, $uid){
  $path_uid_check = db_select('user_menu_visibility','m')
    ->fields('m')
    ->condition('menu_name',$path,'=')
    ->condition('user_id',$uid,'=')
    ->execute();
  $result = $path_uid_check->fetchField();
  if ($result) {
    return TRUE;
  }
}

/**
 * Redirect path.
 */
function menu_per_user_redirect($path) {
  $response = new RedirectResponse($path);
  $response->send();
  exit;
}
