<?php

/**
 * @file
 * Using two hooks to add link to pages and attaching libraries.
 */

use Drupal\Core\Url;
use Drupal\Component\Serialization\Json;

/**
 * Implements hook_page_bottom().
 */
function feedbacks_page_bottom(array &$page_bottom) {

  if (!\Drupal::currentUser()->hasPermission('use feedback form')) {
    return;
  }

  $feedbackBlock = [
    '#type' => 'container',
    '#attributes' => [
      'class' => ['feedback_link bottom'],
    ],
    'link' => [
      '#type' => 'link',
      '#title' => t('Feedback'),
      '#url' => Url::fromRoute('feedbacks_add.form'),
      '#attributes' => [
        'class' => ['use-ajax'],
        'data-dialog-type' => 'modal',
        'data-dialog-options' => Json::encode([
          'width' => '40%',
        ]),
      ],
    ],
  ];

  $page_bottom['feedback'] = $feedbackBlock;

}

/**
 * Implements hook_page_attachments().
 */
function feedbacks_page_attachments(array &$attachments) {
  if (!\Drupal::currentUser()->hasPermission('use feedback form')) {
    return;
  }
  $attachments['#attached']['library'][] = 'feedbacks/feedback-link';
  $attachments['#attached']['library'][] = 'core/drupal.ajax';
}
