<?php
/**
 * @file
 * Contains tm_areachart.module.
 */
use Drupal\Core\Routing\RouteMatchInterface;
/**
 * Implements hook_help().
 */
function tm_barchart_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the tm_barchart module.
    case 'help.page.tm_barchart':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A module to integrate Scatterplot in MarketCaliper') . '</p>';
      return $output;
    default:
  }
}
/**
 * Implements hook_theme().
 */
function tm_barchart_theme() {
  return [
    'tm_barchart' => [
      'template' => 'tm_barchart',
      'render element' => 'children',
    ],
  ];
}