<?php
/**
 * @file
 * Contains tm_wordcloud.module.
 */
use Drupal\Core\Routing\RouteMatchInterface;
/**
 * Implements hook_help().
 */
function tm_wordcloud_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the tm_wordcloud module.
    case 'help.page.tm_wordcloud':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A module to integrate Wordcloud in MarketCaliper') . '</p>';
      return $output;
    default:
  }
}
/**
 * Implements hook_theme().
 */
function tm_wordcloud_theme() {
  return [
    'tm_wordcloud' => [
      'template' => 'tm_wordcloud',
      'render element' => 'children',
    ],
  ];
}