<?php
/**
 * @file
 * Contains tm_narrativetext.module.
 */
use Drupal\Core\Routing\RouteMatchInterface;
/**
 * Implements hook_help().
 */
function tm_narrativetext_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the tm_narrativetext module.
    case 'help.page.tm_narrativetext':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A module to integrate Narrativetext in Tamahagane') . '</p>';
      return $output;
    default:
  }
}
/**
 * Implements hook_theme().
 */
function tm_narrativetext_theme() {
  return [
    'tm_narrativetext' => [
      'template' => 'tm_narrativetext',
      'render element' => 'children',
    ],
  ];
}