<?php
/**
 * @file
 * Contains tm_scatterplot.module.
 */
use Drupal\Core\Routing\RouteMatchInterface;
/**
 * Implements hook_help().
 */
function tm_scatterplot_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the tm_scatterplot module.
    case 'help.page.tm_scatterplot':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A module to integrate Scatterplot in MarketCaliper') . '</p>';
      return $output;
    default:
  }
}
/**
 * Implements hook_theme().
 */
function tm_scatterplot_theme() {
  return [
    'tm_scatterplot' => [
      'template' => 'tm_scatterplot',
      'render element' => 'children',
    ],
  ];
}