<?php
/**
 * @file
 * Contains tm_trendplot.module.
 */
use Drupal\Core\Routing\RouteMatchInterface;
/**
 * Implements hook_help().
 */
function tm_trendplot_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the tm_trendplot module.
    case 'help.page.tm_trendplot':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A module to integrate Trendplot in MarketCaliper') . '</p>';
      return $output;
    default:
  }
}
/**
 * Implements hook_theme().
 */
function tm_trendplot_theme() {
  return [
    'tm_trendplot' => [
      'template' => 'tm_trendplot',
      'render element' => 'children',
    ],
  ];
}
