<?php
/**
 * @file
 * Contains tm_donutchart.module.
 */
use Drupal\Core\Routing\RouteMatchInterface;
/**
 * Implements hook_help().
 */
function tm_donutchart_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the tm_donutchart module.
    case 'help.page.tm_donutchart':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A module to integrate Donutchart in Tamahagane') . '</p>';
      return $output;
    default:
  }
}
/**
 * Implements hook_theme().
 */
function tm_donutchart_theme() {
  return [
    'tm_donutchart' => [
      'template' => 'tm_donutchart',
      'render element' => 'children',
    ],
  ];
}