<?php
/**
 * @file
 * Contains tm_histogram.module.
 */
use Drupal\Core\Routing\RouteMatchInterface;
/**
 * Implements hook_help().
 */
function tm_histogram_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the tm_histogram module.
    case 'help.page.tm_histogram':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A module to integrate Scatterplot in MarketCaliper') . '</p>';
      return $output;
    default:
  }
}
/**
 * Implements hook_theme().
 */
function tm_histogram_theme() {
  return [
    'tm_histogram' => [
      'template' => 'tm_histogram',
      'render element' => 'children',
    ],
  ];
}